import { pgTable, text, timestamp } from "drizzle-orm/pg-core";

// Deliberate placeholder. Task 5 replaces this file wholesale with the
// schema generated by Better Auth, keeping this table's shape.
export const organization = pgTable("organization", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
